AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  ApiLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambdas/api/lambda.handler
      Runtime: nodejs6.10
      Timeout: 60
      MemorySize: 1536
      Policies: AWSLambdaRole
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
